version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '4321:4321'
volumes:
  postgres:
