version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:4321"
volumes:
  postgres:

