version: '3.8'
services:
  app:
      env_file:
        - .env
      build:
        context: .
      links:
        - postgres
      ports:
        - "5555:5555"
  postgres:
    container_name: startapp
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '4321:4321'
volumes:
  postgres:
